theme: jekyll-theme-minimal 
title: Welcome to TrylN3rr’s homepage!  
description: initially, this page will serve as a test env for github pages and jekyll.  
eventually, this site will be the culmination of experimentation and learning.
